[package]
name = "torrust-tracker-located-error"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
thiserror = "1.0"
