[package]
description = "A library to provide error decorator with the location and the source of the original error."
keywords = ["errors", "helper", "library"]
name = "torrust-tracker-located-error"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tracing = "0"

[dev-dependencies]
thiserror = "2"
