[package]
name = "torrust-tracker"
version = "2.2.1"
license = "AGPL-3.0"
authors = ["Mick van Dijke <mick@dutchbits.nl>"]
description = "A feature rich BitTorrent tracker."
edition = "2018"

[profile.release]
lto = "fat"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_bencode = "^0.2.3"
serde_bytes = "0.11"
serde_json = "1.0.72"
hex = "0.4.3"
percent-encoding = "2.1.0"
warp = {version = "0.3", features = ["tls"]}
tokio = {version = "1.7", features = ["macros", "io-util", "net", "time", "rt-multi-thread", "fs", "sync", "signal"]}
binascii = "0.1"
toml = "0.5"
log = {version = "0.4", features = ["release_max_level_info"]}
fern = "0.6"
chrono = "0.4"
byteorder = "1"
r2d2_mysql = "21.0.0"
r2d2_sqlite = "0.16.0"
r2d2 = "0.8.8"
rand = "0.8.4"
config = "0.11"
derive_more = "0.99"
thiserror = "1.0"
aquatic_udp_protocol = { git = "https://github.com/greatest-ape/aquatic" }
futures = "0.3.21"
async-trait = "0.1.52"
btree-slab = "0.4.0"
