[package]
name = "torrust-tracker"
description = "A feature rich BitTorrent tracker."
license-file.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

[workspace.package]
license-file = "COPYRIGHT"
authors = ["Nautilus Cyberneering <info@nautilus-cyberneering.de>, Mick van Dijke <mick@dutchbits.nl>"]
edition = "2021"
repository = "https://github.com/torrust/torrust-tracker"
version = "3.0.0-alpha.3"

[dependencies]
tokio = { version = "1.31", features = ["rt-multi-thread", "net", "sync", "macros", "signal"] }
serde = { version = "1.0", features = ["derive"] }
serde_bencode = "^0.2"
serde_json = "1.0"
serde_with = "3.2"
percent-encoding = "2.2"
binascii = "0.1"
lazy_static = "1.4"
openssl = { version = "0.10", features = ["vendored"] }
config = "0.13"
log = { version = "0.4", features = ["release_max_level_info"] }
fern = "0.6"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
r2d2 = "0.8"
r2d2_mysql = "23.0"
r2d2_sqlite = { version = "0.22", features = ["bundled"] }
rand = "0.8"
derive_more = "0.99"
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1"
aquatic_udp_protocol = "0.8"
uuid = { version = "1", features = ["v4"] }
axum = "0.6.20"
axum-server = { version = "0.5", features = ["tls-rustls"] }
axum-client-ip = "0.4.1"
bip_bencode = "0.4"
torrust-tracker-primitives = { version = "3.0.0-alpha.3", path = "packages/primitives" }
torrust-tracker-configuration = { version = "3.0.0-alpha.3", path = "packages/configuration" }
torrust-tracker-located-error = { version = "3.0.0-alpha.3", path = "packages/located-error" }
multimap = "0.9"
hyper = "0.14"

[dev-dependencies]
mockall = "0.11"
reqwest = { version = "0.11.18", features = ["json"] }
serde_urlencoded = "0.7"
serde_repr = "0.1"
serde_bytes = "0.11"
local-ip-address = "0.5"
torrust-tracker-test-helpers = { version = "3.0.0-alpha.3", path = "packages/test-helpers" }

[workspace]
members = [
    "packages/configuration",
    "packages/primitives",
    "packages/test-helpers",
    "packages/located-error",
]

[profile.dev]
debug = 1
opt-level = 1
lto = "thin"

[profile.release]
debug = 1
opt-level = 3
lto = "fat"
