[package]
edition = "2021"
name = "torrust-tracker"
version = "2.3.0"
license = "AGPL-3.0"
authors = ["Mick van Dijke <mick@dutchbits.nl>"]
description = "A feature rich BitTorrent tracker."
repository = "https://github.com/torrust/torrust-tracker"

[profile.dev]
debug = 1
opt-level = 1
lto = "thin"

[profile.release]
debug = 1
opt-level = 3
lto = "fat"
strip = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "generate_connection_id"
harness = false

[dependencies]
tokio = { version = "1.7", features = ["rt-multi-thread", "net", "sync", "macros", "signal"] }

serde = { version = "1.0", features = ["derive"] }
serde_bencode = "^0.2.3"
serde_json = "1.0.72"
serde_with = "2.0.0"
hex = "0.4.3"
percent-encoding = "2.1.0"
binascii = "0.1"
blake3 = "1.3.1"
cipher = "0.4.3"
blowfish = "0.9.1"
byteorder = "1.4.3"

openssl = { version = "0.10.41", features = ["vendored"] }

warp = { version = "0.3", features = ["tls"] }

config = "0.11"
toml = "0.5"

log = { version = "0.4", features = ["release_max_level_info"] }
fern = "0.6"
chrono = "0.4"

r2d2 = "0.8.8"
r2d2_mysql = "21.0.0"
r2d2_sqlite = { version = "0.21.0", features = ["bundled"] }

rand = "0.8.4"
derive_more = "0.99"
thiserror = "1.0"
futures = "0.3.21"
async-trait = "0.1.52"

aquatic_udp_protocol = "0.2.0"
uuid = { version = "1.1.2", features = ["v4"] }
arraytools = "0.1.5"
