[package]
description = "A library that provides a repository of torrents files and their peers."
keywords = ["library", "repository", "torrents"]
name = "torrust-tracker-torrent-repository"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
aquatic_udp_protocol = "0"
bittorrent-primitives = "0.1.0"
crossbeam-skiplist = "0"
dashmap = "6"
futures = "0"
parking_lot = "0"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal", "sync"] }
torrust-tracker-clock = { version = "3.0.0-develop", path = "../clock" }
torrust-tracker-configuration = { version = "3.0.0-develop", path = "../configuration" }
torrust-tracker-primitives = { version = "3.0.0-develop", path = "../primitives" }
zerocopy = "0.8"

[dev-dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
criterion = { version = "0", features = ["async_tokio"] }
rstest = "0"

[[bench]]
harness = false
name = "repository_benchmark"
