[package]
name = "torrust-tracker-test-helpers"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "macros", "signal"] }
lazy_static = "1.4"
rand = "0.8.5"
torrust-tracker-configuration = {  path = "../configuration"}
