[package]
description = "A library providing helpers for testing the Torrust tracker."
keywords = ["helper", "library", "testing"]
name = "torrust-tracker-test-helpers"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rand = "0"
torrust-tracker-configuration = { version = "3.0.0-beta", path = "../configuration" }
