[package]
name = "torrust-tracker-configuration"
description = "A library to provide configuration to the Torrust Tracker."
license = "AGPL-3.0"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.0"
config = "0.13"
toml = "0.7"
log = { version = "0.4", features = ["release_max_level_info"] }
thiserror = "1.0"
torrust-tracker-primitives = { version = "3.0.0-alpha.2", path = "../primitives" }
torrust-tracker-located-error = { version = "3.0.0-alpha.2", path = "../located-error" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
