[package]
description = "A library to provide configuration to the Torrust Tracker."
keywords = ["config", "library", "settings"]
name = "torrust-tracker-configuration"
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
camino = { version = "1", features = ["serde", "serde1"] }
derive_more = "1"
figment = { version = "0", features = ["env", "test", "toml"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_with = "3"
thiserror = "1"
toml = "0"
torrust-tracker-located-error = { version = "3.0.0-beta-develop", path = "../located-error" }
url = "2"

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
