[package]
name = "torrust-tracker-configuration"
description = "A library to provide configuration to the Torrust Tracker."
keywords = ["library", "config", "settings"]
readme = "README.md"

authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.2"
config = "0.13"
toml = "0.8"
log = { version = "0.4", features = ["release_max_level_info"] }
thiserror = "1.0"
torrust-tracker-primitives = { version = "3.0.0-alpha.6", path = "../primitives" }
torrust-tracker-located-error = { version = "3.0.0-alpha.6", path = "../located-error" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
