[package]
name = "torrust-tracker-primitives"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
derive_more = "0.99"
